FROM jupyter/scipy-notebook

MAINTAINER lbertolini <@lbertolini>

USER root

# bash instead of dash to use source
RUN ln -snf /bin/bash /bin/sh

RUN apt-get update && apt-get install -y \
	libopencv-dev \
        python3-pip \
	python3-opencv && \
    rm -rf /var/lib/apt/lists/*

USER jovyan

RUN pip3 install tensorflow && \
    pip3 install numpy pandas sklearn matplotlib seaborn jupyter pyyaml h5py && \
    pip3 install keras --no-deps && \
    pip3 install opencv-python && \
    pip3 install imutils \
	pip install tensorflow && \
    pip install numpy pandas sklearn matplotlib seaborn jupyter pyyaml h5py && \
    pip install keras --no-deps && \
    pip install opencv-python && \
    pip install imutils

# RUN ["mkdir", "notebooks"]
# COPY conf/.jupyter /jovyan/.jupyter
# COPY run_jupyter.sh /

# Jupyter and Tensorboard ports
EXPOSE 8888 6006

# Store notebooks in this mounted directory
# VOLUME /notebooks

# CMD ["/run_jupyter.sh"]